name: easy_antrag
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # File picker to upload documents
  file_picker: ^5.2.0

  # UI dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
